Analysis:
  process_1:
    name: 'fill_gaps'
    method: 'interpolate'
  process_2:
    name: 'taper'
    method: 'hann'
    max_percentage: 0.05
  process_3:
    name: 'rmean'
    method: 'simple'
  process_4:
    name: 'filter'
    method: 'bandpass'
    freqmin: 4.0
    freqmax: 8.0
  process_5:
    name: 'remove_response'
    inventory: '/home/sysop/Escritorio/geofisica/repositorios/SurfQuakeCore/analysis_config.yaml'
    water_level: 90
    units: 'VEL'
    pre_filt: [0.01,0.02,40,42]



  #shift: [{
  #  name: '/home/sysop/Escritorio/geofisica/test_surfquake/inputs/waveforms_cut/CA.CEST..HHE.D.2022.32',
  #  time: 10
  #}]
