[build-system]
requires = ["setuptools>=61.0", "python-dateutil", "obspy", "pyproj", "pandas"]
build-backend = "setuptools.build_meta"

[project]
name = "surfQuakecore"
version = "0.0.1"
authors = [
  { name="Roberto Cabieces & Thiago Junqueira", email="rcabdia@roa.es"},
]
description = "SurfQuake Core"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://projectisp.github.io/ISP_tutorial.github.io/"